name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node jobs
        uses: actions/setup-node@v4
        with:
          node-version: '20.9'

      - name: Install dependency
        run: npm install

      - name: Run test
        run: npm run test
        env:
          MONGODB_CONNECTION_STRING: ${{secrets.MONGODB_CONNECTION_STRING}}
          CLERK_PUBLISHABLE_KEY: ${{secrets.CLERK_PUBLISHABLE_KEY}}
          CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
          CLERK_FRONTEND_API_URL: ${{secrets.CLERK_FRONTEND_API_URL}}
          CLERK_BACKEND_API_URL: ${{secrets.CLERK_BACKEND_API_URL}}
          CLERK_PEM_PUBLIC_KEY: ${{secrets.CLERK_PEM_PUBLIC_KEY}}
